version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: web-nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - ${WEB_PORT}:80
    networks:
      - lbpapp

  engine:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - lbpapp

  adminer:
    image: adminer
    ports:
      - ${WEB_ADMINER_PORT}:8080
    depends_on:
      - postgres
    networks:
      - lbpapp

  postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lbpapp

networks:
  lbpapp:
    driver: "bridge"
